version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.5
    steps:
      - checkout
      - run: echo 'hi'
      - deploy:
          command: echo 'deploy'
  build2:
    docker:
      - image: busybox
    steps:
      - checkout
      - run: echo 'hello'
